---
- name: "DotNet | {{ ansible_distribution }} | Setting Temp Variables"
  ansible.builtin.set_fact:
    script_cache_dir: /tmp

- name: "DotNet | {{ ansible_distribution }} | Dependencies"
  ansible.builtin.apt:
    name:
      - build-essential
      - git
      - cmake
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - pkg-config
      - unzip
      - ansible-lint
      - ripgrep
    state: latest
  become: true
  become_user: root

- name: "DotNet | {{ ansible_distribution }} | Installation Script"
  ansible.builtin.get_url:
    url: "{{ dotnet_script_url }}"
    dest: "{{ script_cache_dir }}/dotnet-install.sh"
    mode: "0544"
  register: download_result

- name: "DotNet | {{ ansible_distribution }} | Installing versions {{ dotnet_versions }}"
  ansible.builtin.command: "/bin/bash {{ script_cache_dir }}/dotnet-install.sh --version {{ item }}"
  with_items: "{{ dotnet_versions }}"

- name: "DotNet | {{ ansible_distribution }} | Cleanup"
  ansible.builtin.file:
    path: "{{ script_cache_dir }}/dotnet-install.sh"
    state: absent

