export DOTNET_CLI_TELEMETRY_OPTOUT=1

export LANG=en_US.UTF-8
export HYPHEN_INSENSITIVE=true
export ENABLE_CORRECTION=true
export HIST_STAMPS="dd/mm/yyyy"
export ARCHFLAGS="-arch x86_64"
export WINEPREFIX=$HOME/.wine/
export WINEARCH=win64
export DOTNET_ROOT=$HOME/.dotnet
#export XDG_CONFIG_HOME=$HOME/.dotfiles
#export XDG_DATA_DIRS=$HOME/.nix-profile/share:$XDG_DATA_DIRS
export PATH="$PATH:\
$HOME/.dotnet/tools:\
$DOTNET_ROOT:\
$DOTNET_ROOT/tools:\
$HOME/.local/bin:\
$HOME/.cargo/bin:\
$HOME/.cargo/bin/rustc:\
$HOME/.local/share/JetBrains/Toolbox/scripts:\
$HOME/.dotfiles/.foundry/bin"
# export JAVA_HOME=$(readlink -f `which java` | sed "s:/bin/java::")
export EDITOR="nvim"
export LIBVIRT_DEFAULT_URI='qemu:///session'

export TMUX_AUTOSTART=true
export TMUX_OVERRIDE_TERM=false

# ZSH configuration
# export ZSH=$XDG_CONFIG_HOME/oh-my-zsh
export ZSH_THEME="arrow" # See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
export ZSH_TMUX_AUTOSTART=false
export ZSH_TMUX_AUTOSTART_ONCE=false
export ZSH_TMUX_AUTOCONNECT=false
export ZSH_TMUX_AUTOQUIT=false
export ZSH_TMUX_UNICODE=true
# export ZSH_CUSTOM=$XDG_CONFIG_HOME/zsh
# export ZDOTDIR=$ZSH_CUSTOM
# export ZSH_TMUX_ITERM2=true # For iTerm2 Terminal
export _ZO_ECHO='1'

export NVM_DIR="$HOME/.dotfiles/nvm"

unset npm_config_prefix
