---
- name: DotFiles Config
  hosts: all
  become_user: yes

  tasks:
    - name: Setup executable playbooks
      block:
        - name: Find all roles in the roles directory
          ansible.builtin.find:
            paths: "{{ playbook_dir }}/roles"
            file_type: directory
            recurse: no
          delegate_to: localhost
          register: found_roles
          tags:
            - always

        - name: Get dynamic roles
          ansible.builtin.set_fact:
            all_roles: "{{ found_roles.files | map(attribute='path') | map('basename') | list }}"
          tags:
            - always

        - name: Set roles
          ansible.builtin.set_fact:
            run_roles: >-
              {{ playbooks == ['all'] and all_roles or playbooks | difference(exclude_roles | default([])) }}
          tags:
            - always

        - name: Display rules
          ansible.builtin.debug:
            var: run_roles
          tags:
            - always

        - name: Display tags
          ansible.builtin.debug:
            var: ansible_run_tags
          tags:
            - always

        - name: Run roles
          ansible.builtin.include_role:
            name: "{{ roles_item }}"
          loop_control:
            loop_var: roles_item
          loop: "{{ run_roles }}"
          tags:
            - always
