---
- name: "Window-Manager | {{ ansible_distribution }} | Set Facts"
  ansible.builtin.set_fact:
    window_manager_folder: "aerospace"

- name: "Window-Manager | {{ ansible_distribution }} | Install"
  community.general.homebrew_cask:
    name:
      - nikitabobko/tap/aerospace
    state: latest

