---
- name: "Window_Manager | {{ ansible_distribution }} | Checking for Distribution Config: {{ ansible_facts['os_family'] }}"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['os_family'] }}.yml"
  register: distribution_config

- name: "Window_Manager | {{ ansible_distribution }} | Run Tasks: {{ ansible_facts['os_family'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"
  when: distribution_config.stat.exists

- name: "Window_Manager | {{ ansible_distribution }} | Local Config"
  block:
    - name: "Window_Manager | {{ ansible_distribution }} | Create symlink for config files"
      ansible.builtin.file:
        src: "{{ role_path }}/files/{{ window_manager_folder }}/"
        dest: "{{ ansible_user_dir }}/.config/{{ window_manager_folder }}"
        state: link
        force: true
  when: distribution_config.stat.exists and ansible_connection == "local"

- name: "Window_Manager | {{ ansible_distribution }} | Remote Config"
  block:
    - name: "Window_Manager | {{ ansible_distribution }} | Ensure the target directory is present"
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/{{ window_manager_folder }}/"
        state: directory
        force: true
        mode: preserve

    - name: "Window_Manager | {{ ansible_distribution }} | Copy all files to remote"
      ansible.builtin.copy:
        src: "{{ role_path }}/files/{{ window_manager_folder }}/"
        dest: "{{ ansible_user_dir }}/.config/{{ window_manager_folder }}"
        force: true
        mode: preserve
  when: distribution_config.stat.exists and ansible_connection != "local"
