---
- name: "ZSH | Checking for Distribution Config: {{ ansible_facts['os_family'] }}"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['os_family'] }}.yml"
  register: distribution_config
  tags:
    - always

- name: "ZSH | Run Tasks: {{ ansible_facts['os_family'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"
  when: distribution_config.stat.exists
  tags:
    - always

- name: "ZSH | Get all ZSH files"
  delegate_to: localhost
  ansible.builtin.find:
    paths: "{{ role_path }}/files"
    file_type: file
    hidden: true
  register: zsh_files
  tags:
    - always

- name: "ZSH | Local Config"
  when: distribution_config.stat.exists and ansible_connection == "local"
  tags:
    - always
  block:
    - name: "ZSH | Create symlinks to role files"
      ansible.builtin.file:
        src: "{{ item.path }}"
        dest: "{{ ansible_user_dir }}/.{{ item.path | basename }}"
        state: link
        force: true
      loop: "{{ zsh_files.files }}"
      loop_control:
        label: "{{ item.path }}"

- name: "ZSH | Remote Config"
  when: distribution_config.stat.exists and ansible_connection != "local"
  tags:
    - always
  block:
    - name: "ZSH | Copy role files directory to remote"
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "{{ ansible_user_dir }}/.{{ item.path | basename }}"
        force: true
      loop: "{{ zsh_files.files }}"
      loop_control:
        label: "{{ item.path }}"
