- name: "Neovim PPA | {{ ansible_distribution }} | Dependency"
  ansible.builtin.apt:
    name:
      - gpg
    state: latest
  become: true
  become_user: root

- name: "Neovim PPA | {{ ansible_distribution }} | Add PPA Unstable"
  ansible.builtin.apt_repository:
    repo: "ppa:neovim-ppa/unstable"
    state: present
    update_cache: true
  become: true
  become_user: root
