---
- name: "Git | {{ ansible_distribution }} | Checking for Distribution Config: {{ ansible_facts['os_family'] }}"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['os_family'] }}.yml"

- name: "Git | {{ ansible_distribution }} | Run Tasks: {{ ansible_facts['os_family'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"

- name: "Git | {{ ansible_distribution }} | Get all Git config files"
  delegate_to: localhost
  ansible.builtin.find:
    paths: "{{ role_path }}/files"
    file_type: file
    hidden: true
  register: git_config

- name: "Git | {{ ansible_distribution }} | Local Config"
  block:
    - name: "Git | {{ ansible_distribution }} | Create symlinks to role files"
      ansible.builtin.file:
        src: "{{ item.path }}"
        dest: "{{ ansible_user_dir }}/.{{ item.path | basename }}"
        state: link
        force: true
      loop: "{{ git_config.files }}"
      loop_control:
        label: "{{ item.path }}"
  when: ansible_connection == "local"

- name: "Git | {{ ansible_distribution }} | Remote Config"
  block:
    - name: "Git | {{ ansible_distribution }} | Copy role files directory to remote"
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "{{ ansible_user_dir }}/.{{ item.path | basename }}"
        force: true
      loop: "{{ git_config.files }}"
      loop_control:
        label: "{{ item.path }}"
  when: ansible_connection != "local"
