---
- name: "Agent Config | {{ ansible_distribution }} | Install"
  ansible.builtin.debug:
    msg: "Hello"
# - name: "Agent Config | {{ ansible_distribution }} | Install"
#   community.general.homebrew:
#     when: false
#     name:
#       - omp
#     state: latest
