---
- name: "Hotkey-Daemon | {{ ansible_distribution }} | Dependencies"
  ansible.builtin.set_fact:
    hotkey_daemon_folder: "skhd"

- name: "Hotkey-Daemon | {{ ansible_distribution }} | Add skhd tap to Homebrew"
  community.general.homebrew_tap:
    name: koekeishiya/formulae

- name: "Hotkey-Daemon | {{ ansible_distribution }} | Install"
  community.general.homebrew:
    name:
      - skhd
    state: latest

- name: "Hotkey-Daemon | {{ ansible_distribution }} | Start Service"
  command: skhd --start-service
