---
- name: "Tmux | {{ ansible_distribution }} | Dependencies"
  ansible.builtin.apt:
    name:
      - tmux
      - fzf
      - wl-clipboard
      - fd-find
    state: latest
  become: true
  become_user: root
