---
- name: "Tmux | Checking for Distribution Config: {{ ansible_facts['os_family'] }}"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['os_family'] }}.yml"
  register: distribution_config

- name: "Tmux | Run Tasks: {{ ansible_facts['os_family'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"
  when: distribution_config.stat.exists

- name: "Tmux | {{ ansible_distribution }} | Local Config"
  block:
    - name: "Tmux | {{ ansible_distribution }} | Config folder"
      ansible.builtin.file:
        mode: "0755"
        path: "{{ ansible_user_dir }}/.config/tmux"
        state: directory

    - name: "Tmux | {{ ansible_distribution }} | Create symlink for main config file"
      ansible.builtin.file:
        src: "{{ role_path }}/files/tmux.conf"
        dest: "{{ ansible_user_dir }}/.config/tmux/tmux.conf"
        state: link
        force: true

    - name: "Tmux | {{ ansible_distribution }} | Create symlink to plugins directory"
      ansible.builtin.file:
        src: "{{ role_path }}/files/plugins"
        dest: "{{ ansible_user_dir }}/.config/tmux/plugins"
        state: link
        force: true

    - name: "Tmux | {{ ansible_distribution }} | Create symlink to scripts directory"
      ansible.builtin.file:
        src: "{{ role_path }}/files/scripts"
        dest: "{{ ansible_user_dir }}/.config/tmux/scripts"
        state: link
        force: true
  when: distribution_config.stat.exists and ansible_connection == "local"

- name: "Tmux | {{ ansible_distribution }} | Remote Config"
  block:
    - name: "Tmux | {{ ansible_distribution }} | Ensure the target directory is present"
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/tmux/"
        state: directory
        force: true

    - name: "Tmux | {{ ansible_distribution }} | Copy all files to remote"
      ansible.builtin.copy:
        src: "{{ role_path }}/files/"
        dest: "{{ ansible_user_dir }}/.config/tmux"
        force: true
        mode: preserve
  when: distribution_config.stat.exists and ansible_connection != "local"
