---
- name: "Tmux | Checking for Distribution Config: {{ ansible_facts['os_family'] }}"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['os_family'] }}.yml"
  register: distribution_config

- name: "Tmux | Run Tasks: {{ ansible_facts['os_family'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"
  when: distribution_config.stat.exists

- name: "Tmux | {{ ansible_distribution }} | Local Config"
  block:
    - name: "Tmux | {{ ansible_distribution }} | Config folder"
      ansible.builtin.file:
        mode: "0755"
        path: "{{ ansible_user_dir }}/.config/tmux"
        state: directory

    - name: "Tmux | {{ ansible_distribution }} | Create symlink for config files"
      ansible.builtin.file:
        src: "{{ role_path }}/files/"
        dest: "{{ ansible_user_dir }}/.config/tmux"
        state: link
        force: true

    - name: "Tmux | {{ ansible_distribution }} | Install Local TPM Plugins"
      ansible.builtin.command: "{{ ansible_user_dir }}/.config/tmux/plugins/tpm/bin/install_plugins"
  when: distribution_config.stat.exists and ansible_connection == "local"

- name: "Tmux | {{ ansible_distribution }} | Remote Config"
  block:
    - name: "Tmux | {{ ansible_distribution }} | Ensure the target directory is present"
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/tmux/"
        state: directory
        force: true

    - name: "Tmux | {{ ansible_distribution }} | Copy all files to remote"
      ansible.builtin.copy:
        src: "{{ role_path }}/files/"
        dest: "{{ ansible_user_dir }}/.config/tmux"
        force: true
        mode: preserve

    - name: "Tmux | {{ ansible_distribution }} | Install Remote TPM Plugins"
      ansible.builtin.command: "{{ ansible_user_dir }}/.config/tmux/plugins/tpm/bin/install_plugins"
  when: distribution_config.stat.exists and ansible_connection != "local"
