---
- name: "Node | {{ ansible_distribution }} | Setting Temp Variables"
  ansible.builtin.set_fact:
    node_version: "latest"
  tags:
    - always

- name: "Node | {{ ansible_distribution }} | Checking for Distribution Config: {{ ansible_facts['os_family'] }}"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['os_family'] }}.yml"
  register: distribution_config
  tags:
    - always

- name: "Node | Run Tasks: {{ ansible_facts['os_family'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"
  when: distribution_config.stat.exists
  tags:
    - always
