---
- name: "Kitty | {{ ansible_distribution }} | Checking for Distribution Config: {{ ansible_facts['os_family'] }}"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['os_family'] }}.yml"
  register: distribution_config

- name: "Kitty | {{ ansible_distribution }} | Clone themes"
  ansible.builtin.git:
    repo: https://github.com/dexpota/kitty-themes.git
    dest: "{{ role_path }}/files/themes"
    clone: yes
    update: yes
  when: distribution_config.stat.exists

- name: "Kitty | {{ ansible_distribution }} | Run Tasks: {{ ansible_facts['os_family'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"
  when: distribution_config.stat.exists

- name: "Kitty | {{ ansible_distribution }} | Local Config"
  block:
    - name: "Kitty | {{ ansible_distribution }} | Create symlink to role files directory"
      ansible.builtin.file:
        src: "{{ role_path }}/files"
        dest: "{{ ansible_user_dir }}/.config/kitty"
        state: link
        force: true
  when: ansible_connection == "local" and distribution_config.stat.exists

- name: "Kitty | {{ ansible_distribution }} | Remote Config"
  block:
    - name: "Kitty | {{ ansible_distribution }} | Copy role files directory to remote"
      ansible.builtin.copy:
        src: "{{ role_path }}/files/"
        dest: "{{ ansible_user_dir }}/.config/kitty"
        force: true
  when: ansible_connection != "local" and distribution_config.stat.exists
