#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

echo "yabai configuration loaded.."

# Layout
yabai -m config layout bsp
# Rebalance for each new window
# yabai -m config auto_balance new

# Padding and gaps
yabai -m config top_padding 7
yabai -m config bottom_padding 7
yabai -m config left_padding 7
yabai -m config right_padding 7
yabai -m config window_gap 7

# Window

# Spaces (create if doesn't exist)
SPACE_INDEXES=$(yabai -m query --spaces | jq 'map({ (.index|tostring): .label }) | add')

declare -A SPACES_TO_CREATE=(
  [1]="browser"
  [2]="terminal"
  [3]="comms"
  [4]="temp"
  [5]="mail"
  [6]="learning"
  [7]="personal"
)

for INDEX in "${!SPACES_TO_CREATE[@]}"; do
  LABEL="${SPACES_TO_CREATE[$INDEX]}"
  if echo "$SPACE_INDEXES" | jq -e "has(\"$INDEX\")" > /dev/null; then
    yabai -m space "$INDEX" --label "$LABEL"
  else
    yabai -m space --create "$INDEX" && yabai -m space "$INDEX" --label "$LABEL"
  fi
done

# Opacity (requires disabling SIP)
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
# Display orientation
yabai -m config display_arrangement_order default
# Newly created windows managed
yabai -m config window_origin_display default

# Border (requires disabling SIP)
# yabai -m config window_border on
# yabai -m config window_border_width 2
# yabai -m config window_border_color 0xff775759
# yabai -m config active_window_border_color 0xffd75f5f

# Disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
