#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

echo "yabai configuration loaded.."

# Layout
yabai -m config layout bsp
# Rebalance for each new window
# yabai -m config auto_balance new

# Padding and gaps
yabai -m config top_padding 7
yabai -m config bottom_padding 7
yabai -m config left_padding 7
yabai -m config right_padding 7
yabai -m config window_gap 7

# Window

# Spaces (create if doesn't exist)
SPACES=$( yabai -m query --spaces | jq '.[].label' )
[[ $(echo "$SPACES") =~ "browser" ]] || yabai -m space --create 1 && yabai -m space 1 --label browser
[[ $(echo "$SPACES") =~ "terminal" ]] || yabai -m space --create 1 && yabai -m space 2 --label terminal
[[ $(echo "$SPACES") =~ "comms" ]] || yabai -m space --create 1 && yabai -m space 3 --label comms
[[ $(echo "$SPACES") =~ "temp" ]] || yabai -m space --create 1 && yabai -m space 4 --label temp
[[ $(echo "$SPACES") =~ "mail" ]] || yabai -m space --create 1 && yabai -m space 5 --label mail
[[ $(echo "$SPACES") =~ "learning" ]] || yabai -m space --create 1 && yabai -m space 6 --label learning
[[ $(echo "$SPACES") =~ "personal" ]] || yabai -m space --create 1 && yabai -m space 7 --label personal

# Opacity (requires disabling SIP)
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
# Display orientation
yabai -m config display_arrangement_order default
# Newly created windows managed
yabai -m config window_origin_display default

# Border (requires disabling SIP)
# yabai -m config window_border on
# yabai -m config window_border_width 2
# yabai -m config window_border_color 0xff775759
# yabai -m config active_window_border_color 0xffd75f5f

# Disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
