#!/usr/bin/env sh

echo "Prepping yabai configuration..."

# Turn debugging on
# yabai -m config debug_output on
yabai -m config layout bsp
yabai -m config auto_balance x-axis

# Padding and gaps
yabai -m config top_padding 7
yabai -m config bottom_padding 7
yabai -m config left_padding 7
yabai -m config right_padding 7
yabai -m config window_gap 7

# New window spawns to the right if vertical split, or bottom if horizontal split (requires newer version)
yabai -m config window_arrangement_order vertical
yabai -m config window_placement second_child
yabai -m config window_origin_display default
yabai -m config display_arrangement_order default

# Disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Passwords$" manage=off
yabai -m rule --add app="^Sweet Home 3D$" title="^Modify" manage=off
yabai -m rule --add app="^OpenWhispr$" manage=off sticky=on sub-layer=above

echo "User config loaded at $(date)"
