---
- name: "Docker | {{ ansible_distribution }} | Dependencies"
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
  become: true
  become_user: root

- name: "Docker | {{ ansible_distribution }} | Add Docker GPG key"
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.asc
    state: present
  become: true
  become_user: root

- name: "Docker | {{ ansible_distribution }} | Add Docker repo to APT repos"
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    filename: docker
    state: present
  become: true
  become_user: root

- name: "Docker | {{ ansible_distribution }} | Install"
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    force_apt_get: true
    update_cache: true
  become: true
  become_user: root

- name: "Docker | {{ ansible_distribution }} | Start Docker Daemon"
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  become: true
  become_user: root

