---
- name: "Docker | {{ ansible_distribution }} | Dependencies"
  ansible.builtin.apt:
    name: docker
    state: present
  become: true
  become_user: root

- name: "Docker | {{ ansible_distribution }} | Start Docker Daemon"
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  become: true
  become_user: root

