---
- name: "Docker | {{ ansible_distribution }} | Checking for Distribution Config: {{ ansible_facts['os_family'] }}"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['os_family'] }}.yml"
  register: distribution_config
  tags:
    - always

- name: "Docker | {{ ansible_distribution }} | {{ ansible_distribution }} | Run Tasks: {{ ansible_facts['os_family'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"
  when: distribution_config.stat.exists
  tags:
    - always

- name: "Docker | {{ ansible_distribution }} | Local Config"
  when: ansible_connection == "local" and distribution_config.stat.exists
  tags:
    - always
  block:
    - name: "Docker | {{ ansible_distribution }} | Create symlink to role files directory"
      ansible.builtin.file:
        src: "{{ role_path }}/files"
        dest: "{{ ansible_user_dir }}/.config/colima"
        state: link
        force: true

- name: "Docker | {{ ansible_distribution }} | Remote Config"
  when: ansible_connection != "local" and distribution_config.stat.exists
  tags:
    - always
  block:
    - name: "Docker | {{ ansible_distribution }} | Copy role files directory to remote"
      ansible.builtin.copy:
        src: "{{ role_path }}/files/"
        dest: "{{ ansible_user_dir }}/.config/colima"
        force: true
