- name: Install Neovim from GitHub (Release)
  hosts: locally
  vars:
    neovim_install_dir: /opt/nvim
    package_cache_dir: /tmp

  tasks:
    - name: Create the Neovim directory
      ansible.builtin.file:
        path: "{{ neovim_install_dir }}"
        state: directory
        mode: '0755'

    - name: Download the Neovim release archive
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
        dest: "{{ package_cache_dir }}/nvim-linux64.tar.gz"
        mode: '0755'

    - name: Extract the Neovim release archive
      ansible.builtin.unarchive:
        src: "{{ package_cache_dir }}/nvim-linux64.tar.gz"
        dest: "{{ neovim_install_dir }}"
        extra_opts: [--strip-components=1]
        remote_src: true
        keep_newer: true
        mode: '0744'

    - name: Install Neovim build dependencies
      become: yes
      ansible.builtin.apt:
        name:
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - cmake
          - g++
          - pkg-config
          - unzip
        state: present 

    - name: Ensure Neovim is in the system PATH
      ansible.builtin.command: echo 'export PATH=$PATH:{{ neovim_install_dir }}/bin' >> $HOME/.zshrc
      when: not "'{{ neovim_install_dir }}/bin' in ansible_facts['ansible_env']['PATH']"
