- name: Install or Upgrade nvm
  hosts: all
  vars:
    nvm_version: "v0.39.5"
    nvm_install_url: "https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh"
    nvm_dir: "{{ ansible_env.NVM_DIR | default('') }}"

  tasks:
    - name: Download and install NVM
      block:
        - name: Install dependencies
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
          loop:
            - curl
            - wget
            - build-essential 
            - libssl-dev 
            - git-core
            - gcc
            - g++
          become: yes

        - name: Download NVM install script
          ansible.builtin.get_url:
            url: "{{ nvm_install_url }}"
            dest: "/tmp/install_nvm.sh"
            mode: '0755'

        - name: Install NVM
          ansible.builtin.shell: /tmp/install_nvm.sh
          args:
            executable: /bin/sh
          register: nvm_install

        - name: Extract NVM_DIR from command
          ansible.builtin.set_fact:
            nvm_env: "{{ nvm_install.stdout_lines | regex_search('export NVM_DIR=\"([a-zA-Z\\S]*)\"', '\\1') | first | expandvars }}"

        - name: Give nvm.sh executable permissions
          ansible.builtin.file:
            path: "{{ nvm_env }}/nvm.sh"
            state: file
            mode: '0755'

        - name: Load NVM into shell and install Node and NPM
          ansible.builtin.shell: ". {{ nvm_env }}/nvm.sh && nvm install --lts"
          args:
            executable: /bin/sh
          environment:
            NVM_DIR: "{{ nvm_env }}"
      when: nvm_dir == '' 

    - name: Update NVM installation
      block:
        - name: Give nvm.sh executable permissions
          ansible.builtin.file:
            path: "{{ nvm_dir }}/nvm.sh"
            state: file
            mode: '0755'

        - name: Load NVM into shell
          ansible.builtin.shell:
            cmd: "{{ nvm_dir }}/nvm.sh"

        - name: Remove nvm.sh executable permissions
          ansible.builtin.file:
            path: "{{ nvm_dir }}/nvm.sh"
            state: file
            mode: '0644'
      when: nvm_dir != ''

