- name: Install or Upgrade nvm
  hosts: all
  vars:
    nvm_version: "v0.39.7"
    nvm_install_url: "https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh"

  tasks:
    - name: Locate nvm installation directory
      ansible.builtin.shell: echo $NVM_DIR
      register: nvm_dir
      ignore_errors: true

    - name: Check if nvm is installed
      ansible.builtin.shell: "[[ -s '{{ nvm_dir.stdout }}'/nvm.sh ]] && . '{{ nvm_dir.stdout }}'/nvm.sh && nvm --version"
      register: nvm_installed
      when: nvm_dir.stdout != ''
      ignore_errors: true

    - name: Download and run the nvm install script
      block:
        - name: Download nvm install script
          get_url:
            url: "{{ nvm_install_url }}"
            dest: "/tmp/install_nvm.sh"
            mode: '0755'

        - name: Install nvm
          ansible.builtin.shell: /tmp/install_nvm.sh
      when: nvm_dir.stdout == ''

    - name: Install LTS node and npm
      ansible.builtin.shell: "[[ -s '{{ nvm_dir.stdout }}'/nvm.sh ]] && . '{{ nvm_dir.stdout }}'/nvm.sh && nvm install --lts"
      register: node_installed
