- name: Install .NET Core SDK
  hosts: locally

  vars:
    dotnet_script_url: "https://dot.net/v1/dotnet-install.sh"
    script_cache_dir: /tmp
    zshrc_path: "{{ lookup('ansible.builtin.env', 'ZDOTDIR', default='$HOME') + '/.zshrc' }}"
    dotnet_versions:
    - 6.0.100
    - 8

  tasks:
    - name: Download .NET installation script
      ansible.builtin.get_url:
        url: "{{ dotnet_script_url }}"
        dest: "{{ script_cache_dir }}/dotnet-install.sh"
        mode: '0755'
      register: download_result

    - name: Install .NET versions
      ansible.builtin.command: "/bin/bash {{ script_cache_dir }}/dotnet-install.sh --version {{ item }}"
      with_items: "{{ dotnet_versions }}"

    - name: Append DOTNET_ROOT to ~/.zshrc if not in path
      ansible.builtin.lineinfile:
        path: "{{ zshrc_path }}"
        line: export PATH="$PATH:{{ lookup('ansible.builtin.env', 'DOTNET_ROOT') }}/bin"
      when: lookup('ansible.builtin.env', 'DOTNET_ROOT') is not defined
 
  handlers:
    - name: Cleanup on failure
      ansible.builtin.file:
        path: "{{ script_cache_dir }}/dotnet-install.sh"
        state: absent
