- name: Install and compile Neovim from GitHub
  hosts: all
  vars:
    nvim_release_branch: "stable"
    nvim_temp_dir: "/tmp/neovim"

  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - build-essential
        - cmake
        - gettext
        - libtool
        - libtool-bin
        - autoconf
        - automake
        - pkg-config
        - unzip
      become: yes

    - name: Clone Neovim repository
      ansible.builtin.git:
        repo: "https://github.com/neovim/neovim.git"
        dest: "{{ nvim_temp_dir }}"
        version: "{{ nvim_release_branch }}"

    - name: Compile Neovim
      ansible.builtin.shell: make CMAKE_BUILD_TYPE=Release
      args:
        chdir: "{{ nvim_temp_dir }}"

    - name: Create DEB Package
      ansible.builtin.shell: cpack -G DEB
      args:
        chdir: "{{ nvim_temp_dir }}/build"
      become: yes

    - name: Install new Deb package
      ansible.builtin.apt:
        deb: "{{ nvim_temp_dir }}/build/nvim-linux64.deb"
      become: yes

    - name: Cleanup temporary files
      ansible.builtin.file:
        path: "{{ nvim_temp_dir }}"
        state: absent
      become: yes

