- name: Install Nerd Fonts

  tasks:
    - name: Clone Nerd Fonts repository
      git:
        repo: 'git@github.com:ryanoasis/nerd-fonts.git'
        dest: /tmp/nerd-fonts
        clone: yes
        update: no

    - name: Run install.sh from Nerd Fonts
      command: sh /tmp/nerd-fonts/install.sh

    - name: Cleanup - Remove Nerd Fonts directory
      file:
        path: /tmp/nerd-fonts
        state: absent

