---
- name: "Neovim | {{ ansible_distribution }} | Dependencies"
  ansible.builtin.apt:
    name:
      - build-essential
      - git
      - cmake
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - pkg-config
      - unzip
      - ansible-lint
      - ripgrep
    state: present
  become: true
  become_user: root

- name: "Neovim | {{ ansible_distribution }} | Add PPA Stable"
  ansible.builtin.apt_repository:
    repo: "ppa:neovim-ppa/unstable"
    state: present
  become: true
  become_user: root

- name: "Neovim | {{ ansible_distribution }} | Update Cache"
  ansible.builtin.apt:
    update_cache: yes
  become: true
  become_user: root

- name: "Neovim | {{ ansible_distribution }} | Install"
  ansible.builtin.apt:
    name: neovim
    state: present
  become: true
  become_user: root
