---
- name: "Neovim | {{ ansible_distribution }} | Dependencies"
  ansible.builtin.apt:
    name:
      - build-essential
      - git
      - cmake
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - pkg-config
      - unzip
      - ansible-lint
      - ripgrep
      - fd-find
    state: latest
  become: true
  become_user: root

- name: "Neovim | {{ ansible_distribution }} | Add PPA Unstable"
  ansible.builtin.apt_repository:
    repo: "ppa:neovim-ppa/unstable"
    state: present
  become: true
  become_user: root

- name: "Neovim | {{ ansible_distribution }} | Update Cache & Install"
  ansible.builtin.apt:
    name: neovim
    state: latest
    force: true
    update-cache: true
  become: true
  become_user: root
