---
- name: "Neovim | {{ ansible_distribution }} | Dependencies"
  ansible.builtin.apt:
    name:
      - build-essential
      - git
      - cmake
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - pkg-config
      - unzip
      - ansible-lint
      - ripgrep
    state: present
  become: true
  become_user: root

- name: "Neovim | {{ ansible_distribution }} | Cloning Repository"
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ nvim_temp_dir }}"
    version: "{{ nvim_release_branch }}"

- name: "Neovim | {{ ansible_distribution }} | Compiling"
  ansible.builtin.shell: make CMAKE_BUILD_TYPE=Release
  args:
    chdir: "{{ nvim_temp_dir }}"

- name: "Neovim | {{ ansible_distribution }} | Creating DEP Package"
  ansible.builtin.shell: cpack -G DEB
  args:
    chdir: "{{ nvim_temp_dir }}/build"
  become: true

- name: "Neovim | {{ ansible_distribution }} | Installing DEP Package"
  ansible.builtin.apt:
    deb: "{{ nvim_temp_dir }}/build/nvim-linux64.deb"
  become: true

- name: "Neovim | {{ ansible_distribution }} | Cleanup"
  ansible.builtin.file:
    path: "{{ nvim_temp_dir }}"
    state: absent
  become: true
