---
# noqa package-latest
- name: "Neovim | {{ ansible_distribution }} | Dependencies"
  ansible.builtin.apt:
    name:
      - build-essential
      - git
      - cmake
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - pkg-config
      - unzip
      - fzf
      - ansible-lint
      - ripgrep
      - fd-find
      - wl-clipboard
    state: latest
  become: true
  become_user: root

# TODO: Check if npm is present and install from package manager if not

- name: "Neovim | {{ ansible_distribution }} | Add Apt Repository"
  ansible.builtin.include_tasks: ../meta/add_neovim_repo.yml

# noqa package-latest
- name: "Neovim | {{ ansible_distribution }} | Update Cache & Install"
  ansible.builtin.apt:
    name: neovim
    state: latest
  become: true
  become_user: root
