---
- name: "Neovim | {{ ansible_distribution }} | Setting Temp Variables"
  ansible.builtin.set_fact:
    cacheable: true
    nvim_release_branch: "latest"

- name: "Neovim | {{ ansible_distribution }} | Checking for Distribution Config: {{ ansible_facts['os_family'] }}"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['os_family'] }}.yml"
  register: distribution_config

- name: "Neovim | {{ ansible_distribution }} | Local Config"
  block:
    - name: "Neovim | Config folder"
      ansible.builtin.file:
        mode: "0755"
        path: "{{ ansible_user_dir }}/.config/nvim"
        state: directory

    - name: "Neovim | {{ ansible_distribution }} | Create symlink to role files directory"
      ansible.builtin.file:
        src: "{{ role_path }}/files"
        dest: "{{ ansible_user_dir }}/.config/nvim"
        state: link
        force: true

    - name: "Neovim | {{ ansible_distribution }} | Install/Update Plugins"
      ansible.builtin.command: nvim --headless -c 'Lazy sync' -c 'qall'
  when: distribution_config.stat.exists and ansible_connection == "local"

- name: "Neovim | {{ ansible_distribution }} | Remote Config"
  block:
    - name: "Neovim | {{ ansible_distribution }} | Ensure the target directory is present"
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/nvim"
        state: directory
        force: true

    - name: "Neovim | {{ ansible_distribution }} | Copy role files directory to remote"
      ansible.builtin.copy:
        src: "{{ role_path }}/files/"
        dest: "{{ ansible_user_dir }}/.config/nvim"
        force: true

    - name: "Neovim | {{ ansible_distribution }} | Run setup"
      ansible.builtin.command: nvim --headless -c 'Lazy sync' -c 'qall'
  when: distribution_config.stat.exists and ansible_connection != "local"
