---
- name: "Neovim | Checking for Distribution Config: {{ ansible_facts['os_family'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['os_family'] }}.yml"
  register: neovim_distribution_config

- name: Debug
  ansible.builtin.debug:
    msg: "{{neovim_distribution_config}}"

- name: "Neovim | Run Tasks: {{ ansible_facts['os_family'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"
  when: neovim_distribution_config.stat.exists

- name: "Neovim | Local Config"
  block:
    - name: "Neovim | Config folder"
      ansible.builtin.file:
        mode: "0755"
        path: "{{ ansible_user_dir }}/.config/nvim"
        state: directory

    - name: "Neovim | Create symlink to role files directory"
      ansible.builtin.file:
        src: "{{ role_path }}/files"
        dest: "{{ ansible_user_dir }}/.config/nvim"
        state: link
        force: true
  when: ansible_connection == "local"

- name: "Neovim | Remote Config"
  block:
    - name: "Neovim | Copy role files directory to remote"
      ansible.builtin.copy:
        src: "{{ role_path }}/files/"
        dest: "{{ ansible_user_dir }}/.config/nvim"
        force: true
  when: ansible_connection != "local"
