---
- name: "System Update | {{ ansible_distribution }} | Update Homebrew"
  community.general.homebrew:
    update_homebrew: true
  register: homebrew_update_result
  changed_when: "'Homebrew already up-to-date' not in homebrew_update_result.msg"

- name: "System Update | {{ ansible_distribution }} | Update Homebrew packages"
  community.general.homebrew:
    upgrade_all: true
  register: homebrew_packages_update_result
  changed_when: "'Homebrew packages already upgraded' not in homebrew_packages_update_result.msg"

- name: "System Update | {{ ansible_distribution }} | Update Homebrew Casks"
  community.general.homebrew_cask:
    upgrade_all: true
  register: homebrew_casks_update_result
  changed_when: "'Homebrew casks already upgraded' not in homebrew_casks_update_result.msg"

- name: "System Update | {{ ansible_distribution }} | Update Apps from App Store"
  command: mas upgrade
  register: mas_upgrade_result
  changed_when: "'No pending updates' not in mas_upgrade_result.stdout"

- name: "System Update | {{ ansible_distribution }} | Update Neovim config"
  ansible.builtin.shell: nvim --headless "+Lazy! sync" "+TSUpdate" "+MasonUpdateAll" +qa

- name: "System Update | {{ ansible_distribution }} | Update ZInit"
  ansible.builtin.shell: |
    source $HOME/.zshrc
    source $HOME/.zshenv

    zinit update -a -p
  args:
    executable: /bin/zsh

# - name: "System Update | {{ ansible_distribution }} | Check for Software Updates"
#   ansible.builtin.command: softwareupdate -l
#   register: update_list
#   become: yes
#   become_user: root
#
# - name: "System Update | {{ ansible_distribution }} | Download System Update"
#   ansible.builtin.command: softwareupdate -d -a --agree-to-license
#   become: yes
#   become_user: root
#   when: update_list.stdout.find("No new software available") == -1
#
# - name: "System Update | {{ ansible_distribution }} | Install System Update"
#   ansible.builtin.command: softwareupdate -i --agree-to-license
#   become: yes
#   become_user: root
#   when: update_list.stdout.find("No new software available") == -1
