---
- name: "Fonts | {{ ansible_distribution }} | Setting Temp Variables"
  ansible.builtin.set_fact:
    script_cache_dir: "/tmp"
    user_fonts_dir: "{{ ansible_env.HOME }}/Library/Fonts"

- name: "Fonts | {{ ansible_distribution }} | Get all Nerd Fonts"
  ansible.builtin.shell: brew search /font-\.\*-nerd-font/ | cut -d'/' -f3
  register: "fonts"

- name: "Fonts | {{ ansible_distribution }} | Get all Nerd Fonts"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ fonts.stdout_lines }}"
