---
- name: "Fonts | Checking for Distribution Config: {{ ansible_facts['os_family'] }}"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['os_family'] }}.yml"
  register: fonts_distribution_config

- name: "Fonts | {{ ansible_distribution }} | Install Fonts"
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"
  when: fonts_distribution_config.stat.exists
